### ISSUE TITLE
openj9 branch java -version jdk- tag level finding tags across all branches

### ISSUE THREAD

**Issue by andrew-m-leonard** [ibmruntimes/openj9-openjdk-jdk#101]
The custom-hook.m4 logic to determine the "based -on <jdk-tag>" queries all jdk matching tags across the whole repo, meaning if more recent levels have been merged into master, then a build of openj9 branch which does not have those reachable will still display them.
Eg.jdk11 openj9 branch is in fact at jdk-11.0.3+2, but as master & openj9-0.14 have jdk-11.0.3+7 it incorrectly chooses that level.

**Comment by pshipton** [comment]
@keithc-ca

**Comment by keithc-ca** [comment]
@andrew-m-leonard Can you give an example scenario where it goes wrong (specific SHA checkout out in the presence of specific tags)?

**Comment by andrew-m-leonard** [comment]
For example jdk11 "openj9" branch is actually based on "jdk-11.0.3+2", but
nightly Adopt builds show jdk-11.0.3+7
https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-linux-x64-openj9/210/console
