### ISSUE TITLE
Changes to openj9 branch cause (unnecessary) acceptance builds

### ISSUE THREAD

**Issue by pshipton** [ibmruntimes/openj9-openjdk-jdk#115]
Any time there is a change to the openj9 branch in an extensions repo, the staging branch is updated as well by the automated merge process, and this causes an unnecessary acceptance build to occur.

**Comment by pshipton** [comment]
@andrew-m-leonard @AdamBrousseau

**Comment by pshipton** [comment]
Examples are
https://ci.eclipse.org/openj9/view/Pipelines/job/Pipeline-OpenJDK11-Acceptance/17/
https://ci.eclipse.org/openj9/view/Pipelines/job/Pipeline-OpenJDK11-Acceptance/18/

**Comment by andrew-m-leonard** [comment]
These look fine, they are both triggered from nightly merge to staging jobs, respectively:

**Comment by andrew-m-leonard** [comment]
Remember also that openj9-staging may get new changes from the openj9 branch during a nightly merge-to-staging branch, which is necessary as openj9-staging builds with "latest" Eclipse/openj9 so has to build with latest openj9 branch, eg.for recent GPUHandlerMethod dependent changes...

**Comment by pshipton** [comment]
They aren't testing anything new. They are wasting valuable machine time running acceptance builds on code which is already tested via the nightly build. Not sure we have enough machine power to run the testing that should be run, so wasting time running unnecessary things is not ideal.

**Comment by AdamBrousseau** [comment]
I see the need to keep the `staging` branch in sync with the `openj9` branch but imo we only need to push it up if there is new content from `master`. Nobody will be building the staging branch so if it is out of date until the next refresh from `master` I think that is fine.

**Comment by andrew-m-leonard** [comment]
ok, that seems reasonable, I can change the merge-to-staging script to only merge openj9 if new master content... and also don't try and build if nothing merged so as to prevent alarming unecessary build failures... i'll work on that

**Comment by andrew-m-leonard** [comment]
@AdamBrousseau @pshipton one thought crossed my mind, what if the AcceptanceJob fails for whatever reason, what will trigger the job again if no new master push occurs? can some "state" be stored that would indicate it needs to be re-tried or something resolving? or would we rely on a manual re-submit?

**Comment by pshipton** [comment]
It is up to the build monitor(s) to keep an eye on it and take appropriate action (which I have done in the past for jdknext). If the acceptance failure is posted to jenkins then this is easy. If the acceptance fails quietly, it likely won't be noticed, at least not for some time. As we get closer to a release, there will be more attention on making sure the latest levels are integrated. I think we have all the "state" we need, it is obvious looking at the openj9-staging branch and the acceptance builds what is going on.

**Comment by andrew-m-leonard** [comment]
i've updated the merge scripts, it will only update openj9-staging if new master changes are available to be merged...

**Comment by pshipton** [comment]
Thanks, closing then.
