### ISSUE TITLE
Include debug symbols in the SDK

### ISSUE THREAD

**Issue by hangshao0** [ibmruntimes/openj9-openjdk-jdk#155]
See discussions here:
https://github.com/eclipse/openj9/issues/7827#issuecomment-557604842
https://github.com/eclipse/openj9/issues/7827#issuecomment-557640294

Currently we do not zip the debug symbols into the SDKs built at https://ci.eclipse.org/openj9/, making it hard to see the native stack information from a core file generated from a test failure.

**Comment by hangshao0** [comment]
FYI: @DanHeidinga, @pshipton

**Comment by pshipton** [comment]
@keithc-ca

**Comment by keithc-ca** [comment]
Debug symbols are now available.
