### ISSUE TITLE
Have builds print the SHAs being used

### ISSUE THREAD

**Issue by pshipton** [ibmruntimes/openj9-openjdk-jdk#242]
Looking at https://github.com/AdoptOpenJDK/openjdk-build/issues/2178, it's a failure to build the JVM, so there is no -version output. I don't see anywhere in the output where the OpenJ9 and OMR SHAs are shown. The get_j9_source.sh script could print them out after doing a clone. 

The OpenJ9 builds determine the SHAs ahead of time and specify them to the script, but Adopt and other builds don't do this.

**Comment by pshipton** [comment]
@keithc-ca

**Comment by keithc-ca** [comment]
As I started working on this, I noticed that the openjdk SHA is computed only at configuration time, while the openj9 and omr SHAs are computed at build time. I plan to remove this inconsistency by computing all three SHAs (only) at configuration time. Printing the results at configuration time should then be sufficient.

**Comment by keithc-ca** [comment]
Here's a sample of the new configuration output (for jdk11):
```
checking for m4... /usr/bin/m4
Source versions:
  openjdk - 7e023948526
  openj9  - 015d3630dec
  omr     - e2fac34fcb3
checking CUDA_HOME... /home/keithc/opt/cuda-11.0
```

**Comment by keithc-ca** [comment]
Do you think it should be the other way around (openjdk SHA is computed at build time)?

**Comment by andrewcraik** [comment]
I personally think it should be the other way (eg build time) - doing partial builds is par for the course doing JIT development and I worry that if the version is not computed at build time doubt about what is actually in a build will creep in which will cost development time and needless confusion - right now we can trust the version in the string is the version that was used to build 100% and I worry the configure-time option loses that fidelity and unambiguous trust we can place in the SHAs today.

**Comment by AdamBrousseau** [comment]
I'm not familiar with all dev workflows but I just wanted to say that build time sha is not necessarily 100% accurate. The files can still be modified by hand and not committed to Git. If you wanted 100% you could build into your SHA check a Git status check and print some kind of asterisk * with the SHA if the status was not clean. But maybe that's an edge case not worth solving?

**Comment by DanHeidinga** [comment]
> Do you think it should be the other way around (openjdk SHA is computed at build time)?

+1 from me.  Having all the SHAs reflect what was built makes the most sense.  While both approaches are acceptable for the Adopt builds as they start from a clean slate each time, I agree with Andrew that incremental builds are more common for developer workflows.  Better to accurately list the SHAs in `-version` to avoid confusion when comparing builds.

**Comment by keithc-ca** [comment]
If we agree to use build-time SHAs (that seems to be the consensus we're approaching), then eclipse/openj9#9658 will want more attention so those incremental builds don't take longer than they should.

**Comment by keithc-ca** [comment]
This can be closed once these are merged:
* ibmruntimes/openj9-openjdk-jdk8#455
* ibmruntimes/openj9-openjdk-jdk11#357
* ibmruntimes/openj9-openjdk-jdk15#40
* #244
