### ISSUE TITLE
Contribute #260 to OpenJDK

### ISSUE THREAD

**Issue by pshipton** [ibmruntimes/openj9-openjdk-jdk#261]
https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/260 should be contributed to OpenJDK.
@andrew-m-leonard

**Comment by andrew-m-leonard** [comment]
This is now merged into jdk: https://github.com/openjdk/jdk/commit/12ccd211f2944e8c2d03dfdafef3bac9f9ce774b
@pshipton @JasonFengJ9

**Comment by pshipton** [comment]
Thanks!

**Comment by pshipton** [comment]
I'll keep this open for any required cleanup.

**Comment by pshipton** [comment]
Clean up https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/273
