### ISSUE TITLE
Number of cpus on AIX isn't determined correctly

### ISSUE THREAD

**Issue by AdamBrousseau** [ibmruntimes/openj9-openjdk-jdk#29]
Copied from ibmruntimes/openj9-openjdk-jdk8#57

If smt is enabled the correct number of processors is not correct on configure.

There are a number of ways that can be used to determine actual number of processors, I found this works for me on the systems I have access to, smt enabled or not at time of configure

`--with-jobs='pmcycles -m | wc -l | awk '{print $1}''`

**Comment by andrew-m-leonard** [comment]
Contributed to openjdk already
