### ISSUE TITLE
Missing TEST.groups file needed to enable AGCT unit testing

### ISSUE THREAD

**Issue by smlambert** [ibmruntimes/openj9-openjdk-jdk#331]
This issue relates to https://github.com/eclipse-openj9/openj9/issues/12276#issuecomment-866010701

For jdk8, serviceability tests are defined in [hotspot_serviceability](https://github.com/adoptium/aqa-tests/blob/master/openjdk/playlist.xml#L124) target.  When attempting to run this target against openj9, there appears not be a hotspot/test/TEST.groups file where this target is normally defined in a typical jdk8u mirror (see: https://github.com/AdoptOpenJDK/openjdk-jdk8u/blob/master/hotspot/test/TEST.groups#L141-L142).

From https://openj9-jenkins.osuosl.org/view/Test/job/Grinder/80/console: 
```
12:47:58  Error: Group spec does not specify a valid test suite: /home/jenkins/workspace/Grinder/aqa-tests/TKG/../openjdk/openjdk-jdk/hotspot/test:hotspot_serviceability
12:47:58  
12:47:58  hotspot_serviceability_1_FAILED
```

<img width="332" alt="Screen Shot 2021-06-22 at 1 53 25 PM" src="https://user-images.githubusercontent.com/2836948/122975658-94670500-d361-11eb-983b-1ee2dbcb6752.png">
<img width="272" alt="Screen Shot 2021-06-22 at 1 53 53 PM" src="https://user-images.githubusercontent.com/2836948/122975660-94ff9b80-d361-11eb-95d7-ffcda9875a06.png">

**Comment by smlambert** [comment]
Presumably I should have created this issue in https://github.com/ibmruntimes/openj9-openjdk-jdk8

**Comment by pshipton** [comment]
@JasonFengJ9 can you pls look at fixing this so we automatically mirror this file for all versions.

**Comment by JasonFengJ9** [comment]
It appears only JDK8 doesn't have the `TEST.groups` for `hotspot`.
```
JDK - https://github.com/ibmruntimes/openj9-openjdk-jdk/blob/openj9/test/hotspot/jtreg/TEST.groups
JDK17 - https://github.com/ibmruntimes/openj9-openjdk-jdk17/blob/openj9/test/hotspot/jtreg/TEST.groups
JDK16 - https://github.com/ibmruntimes/openj9-openjdk-jdk16/blob/openj9/test/hotspot/jtreg/TEST.groups
JDK11 - https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/openj9/test/hotspot/jtreg/TEST.groups
```
Note: it is under `hotspot/jtreg` which is same as `OpenJDK`.

I will fix `JDK8` and refer this issue instead.

**Comment by pshipton** [comment]
@smlambert since only jdk8 is missing the file, I assume we can enable the tests for jdk11+ now?

**Comment by JasonFengJ9** [comment]
`JDK8` `hotspot` directory is completely filter out, it is `hg` based and requires more considerations.

**Comment by pshipton** [comment]
jdk11 is hg based and includes (all?) test/hotspot files. Seems jdk8 can do the same (include all test files), but I guess jdk8 has a different directory structure with hotspot at the top level rather than using test/hotspot.

**Comment by JasonFengJ9** [comment]
As per https://github.com/eclipse-openj9/openj9/issues/12276#issuecomment-875697978
_AsyncGetCallTrace (ASGCTBaseTest) is a sub-test of hotspot_serviceability. From what I can see, AsyncGetCallTrace (ASGCTBaseTest) only exists in 16+. It does not exist in JDK11. This means we can only run AsyncGetCallTrace (ASGCTBaseTest) for JDK16+._

So there is no need to add `JDK8` `hotspot` directory for `ASGCTBaseTest`.

**Comment by pshipton** [comment]
Ok. Closing this.
