### ISSUE TITLE
Rename github.com:ibmruntimes/openj9-openjdk-jdk "jdk" & "openj9-jdk" branches to be consistent

### ISSUE THREAD

**Issue by andrew-m-leonard** [ibmruntimes/openj9-openjdk-jdk#48]
Rename github.com:ibmruntimes/openj9-openjdk-jdk "jdk" & "openj9-jdk" branches to be consistent with jdk 8/9/10/11, where they are called master & openj9

- [x] 1. Initally duplicate the branches ie. jdk->master, openj9-jdk->openj9
- [x] 2. Communicate about using new branches, and update auto-merge to push to new branches, and any build jobs.
- [x] 3. Delete the old branches

**Comment by pshipton** [comment]
Please also announce the change on the OpenJ9 Slack so that people with existing clones can be aware.

**Comment by andrew-m-leonard** [comment]
Done
