### ISSUE TITLE
openjdk-tag.gmk:OPENJDK_TAG doesn't match actual openjdk tag merged

### ISSUE THREAD

**Issue by JasonFengJ9** [ibmruntimes/openj9-openjdk-jdk#528]
Current `openjdk-tag.gmk` content:
```
OPENJDK_TAG := jdk-20+25
```
https://github.com/ibmruntimes/openj9-openjdk-jdk/blob/fcde6293720df8a20efd65fb505accf0340604b9/closed/openjdk-tag.gmk#L1

[jdk-20+26](https://github.com/ibmruntimes/openj9-openjdk-jdk/releases/tag/jdk-20%2B26) is already in the repo.

This is a mismatch, `openjdk-tag.gmk` missed a update.

**Comment by keithc-ca** [comment]
Fixed via #527.
