### ISSUE TITLE
Extension test change is not picked up by PR builds.

### ISSUE THREAD

**Issue by JasonFengJ9** [ibmruntimes/openj9-openjdk-jdk#613]
https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/670#issuecomment-1589735362
```
Strange: the test job didn't use this change; instead it used the [current openj9 branch - b33416dc888](https://github.com/ibmruntimes/openj9-openjdk-jdk11/commit/b33416dc888ee757c6761810bf416f37c6b17e8a).

I think this is a known issue as well, the test change is not picked up, it was determined a low priority item.

```

FYI @AdamBrousseau

**Comment by pshipton** [comment]
@JasonFengJ9 Issues should be created in the OpenJ9 repo for proper tracking. That is where the PR build code is as well.

Looking at a grinder, the parameters for test are JDK_REPO and JDK_BRANCH. At the top level job (https://openj9-jenkins.osuosl.org/job/Pipeline_Build_Test_JDK11_aarch64_linux/1475/console) we see
`09:39:38  Using OPENJDK_REPO = https://github.com/ibmruntimes/openj9-openjdk-jdk11.git OPENJDK_BRANCH = openj9 OPENJDK_SHA = b33416dc888ee757c6761810bf416f37c6b17e8a`
In the test job (https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.openjdk_aarch64_linux_Personal/20/consoleFull), there is no mention of these parameters.

**Comment by AdamBrousseau** [comment]
So the ask is that any PR build that changes code in extensions, should pass JDK_REPO & JDK_BRANCH to the test jobs. Correct? I'm not sure I was thinking of the same known issue originally.
Does the test code have ability at the moment to fetch PR refs and checkout a merge ref of extensions repos @llxia?

**Comment by JasonFengJ9** [comment]
I think the original issue was
* https://github.com/ibmruntimes/openj9-openjdk-jdk/issues/506

**Comment by pshipton** [comment]
Again, that's in the wrong repo. Pls open an issue at https://github.com/eclipse-openj9/openj9/issues

**Comment by JasonFengJ9** [comment]
https://github.com/ibmruntimes/openj9-openjdk-jdk/issues/506#issuecomment-1276579336

It was tracked at [infrastructure/issues/7363](https://github.ibm.com/runtimes/infrastructure/issues/7363) unless an openj9 issue helps.

**Comment by pshipton** [comment]
Everything here is open source, the code that needs to be changed is open source in the OpenJ9 repo.

**Comment by JasonFengJ9** [comment]
Created
* https://github.com/eclipse-openj9/openj9/issues/17595
