### ISSUE TITLE
CopyrightCheck jobs do not cleanWs()

### ISSUE THREAD

**Issue by AdamBrousseau** [ibmruntimes/openj9-openjdk-jdk#79]
This causes the jobs to consume valuable space on our worker machine.

Recommend adding a try/finally block around the code.

```
node ('worker') {
    try {
        // Stuff
    } finally {
        cleanWs()
    }
}
```
Disabled the jobs temporarily
https://ci.eclipse.org/openj9/view/Infrastructure/job/CopyrightCheck-OpenJDK/
https://ci.eclipse.org/openj9/view/Infrastructure/job/CopyrightCheck-OpenJDK12/
https://ci.eclipse.org/openj9/view/Infrastructure/job/CopyrightCheck-OpenJDK11/
https://ci.eclipse.org/openj9/view/Infrastructure/job/CopyrightCheck-OpenJDK8/

**Comment by pshipton** [comment]
@lumpfish @andrew-m-leonard

**Comment by lumpfish** [comment]
PR submitted: https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/80

Test run at: https://ci.eclipse.org/openj9/view/Sandbox/job/CopyrightCheck-OpenJDK11-Simon/88/console
